import avatar01 from "../assets/image/avatar/avatar01.jpg";
import avatar02 from "../assets/image/avatar/avatar02.jpg";
import avatar03 from "../assets/image/avatar/avatar03.jpg";
import NFT1 from "../assets/image/NFT1.jpg";
import NFT2 from "../assets/image/NFT2.jpg";
import NFT3 from "../assets/image/NFT3.jpg";
import NFT4 from "../assets/image/NFT4.jpg";
import NFT5 from "../assets/image/NFT5.jpg";
import NFT6 from "../assets/image/NFT6.jpg";
import NFT7 from "../assets/image/NFT7.jpg";
import NFT8 from "../assets/image/NFT8.jpg";
import NFT9 from "../assets/image/NFT9.jpg";

export const DATA =[
    {
        id: "1",
        name: "Cryptopunk #240",
        creator: "Cryptopunk",
        price: 4.25,
        views: "1.5K",
        comments: 12,
        image: NFT1,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "2",
        name: "Great Ape #6494",
        creator: "Great Ape",
        price: 7.25,
        views: "1.5K",
        comments: 12,
        image: NFT2,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "3",
        name: "Meebit #2325",
        creator: "Meebit",
        price: 95.25,
        views: "1.5K",
        comments: 12,
        image: NFT3,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "4",
        name: "Kodala Agent",
        creator: "Kodala Agent #1564",
        price: 54.25,
        views: "1.5K",
        comments: 12,
        image: NFT4,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "5",
        name: "Meebit #2375",
        creator: "Meebit",
        price: 10.25,
        views: "1.5K",
        comments: 12,
        image: NFT5,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "6",
        name: "Cryptopunk #4740",
        creator: "Cryptopunk",
        price: 20.25,
        views: "1.5K",
        comments: 12,
        image: NFT6,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "7",
        name: "Cryptopunk #470",
        creator: "Cryptopunk",
        views: "1.5K",
        comments: 12,
        price: 18.25,
        image: NFT7,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "8",
        name: "Great Ape #494",
        creator: "Great Ape",
        views: "1.5K",
        comments: 12,
        price: 18.25,
        image: NFT8,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "9",
        name: "Great Ape #6434",
        creator: "Great Ape",
        views: "1.5K",
        comments: 12,
        price: 18.25,
        image: NFT9,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "10",
        name: "Kodala Agent",
        creator: "Kodala Agent #1164",
        views: "1.5K",
        comments: 12,
        price: 18.25,
        image: NFT1,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
      {
        id: "11",
        name: "Kodala Agent",
        creator: "Kodala Agent #1864",
        views: "1.5K",
        comments: 12,
        price: 18.25,
        image: NFT2,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
    
      {
        id: "12",
        name: "Koala Anent",
        creator: "Koala Anent #1584",
        views: "1.5K",
        comments: 12,
        price: 18.25,
        image: NFT3,
        date: "21.04.2022",
        topBid: "10,5221",
        address: "0x245cf...adew",
        tokenId: 10216,
        tokenSt: "ERC-721",
        blockchain: "Ethereun",
        avatars: [
          { id: "1", image: avatar01 },
          { id: "2", image: avatar02 },
          { id: "3", image: avatar03 },
        ],
      },
   ]